---
MetaDataFormat: "yaml"
baseurl: "http://sookocheff.com"
title: "Kevin Sookocheff"
disqusShortname: "kevinsookocheff"
languageCode: "en-us"
copyright: "Copyright Kevin Sookocheff."
author:
  name: "Kevin Sookocheff"
  email: "kevin.sookocheff@gmail.com"
Taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"
